### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by praveendiwakar1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-p12-pem/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by praveendiwakar1** [comment]
https://github.com/googleapis/google-p12-pem/issues/397

**Comment by praveendiwakar1** [comment]
@SurferJeffAtGoogle Please review and merge the changes.

**Comment by praveendiwakar1** [comment]
@yoshi-kokoro Please help here as we are blocked due to this.

**Comment by bcoe** [comment]
Addressed in #403

**Pull request closed without merging**
